=== sportradar/MtsSdkNet/docs/client_api/access-token-schema.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "type":"object",
  "additionalProperties":false,
  "properties":{
    "access_token":{
      "type":"string"
    },
    "expires_in":{
      "type":"integer"
    },
    "not-before-policy":{
      "type":"integer"
    },
    "refresh_expires_in":{
      "type":"integer"
    },
    "refresh_token":{
      "type":"string"
    },
    "session_state":{
      "type":"string"
    },
    "token_type":{
      "type":"string"
    },
    "scope":{
      "type":"string"
    }
  }
}

=== sportradar/MtsSdkNet/src/Sportradar.MTS.SDK.Test/TESTDATA/auth-token.json
{ "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJsb3BNd1hBdHZTNXh2MWswLUNPWnZTWHhzWFdFdnZCMDdQdFk2WjJDVFc4In0.eyJleHAiOjE2MTYxNTI3ODcsImlhdCI6MTYxNjE0OTE4NywianRpIjoiMzQ2MWY1MzgtNzY3NS00YjQ4LThkZjMtOGI4ODhhM2RiZDA0IiwiaXNzIjoiaHR0cHM6Ly9tdHMtYXV0aC1jaS5iZXRyYWRhci5jb20vYXV0aC9yZWFsbXMvbXRzIiwiYXVkIjpbIm10cy1lZGdlLWV4dCIsIm10cy1hcGktZ2F0ZXdheSIsImFjY291bnQiXSwic3ViIjoiOTA4MTE5NDQtNGY4MS00NDZkLThiZjQtZmU4NmI1ZjYwZWZhIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibXRzLWVkZ2UtaW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjVmNjFmYTkyLTRjMWEtNGFlZC1iZWMwLTBlN2MyZDdmZGM5ZiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly90cy1jaS1rOHMuYmV0cmFkYXIuY29tIiwiaHR0cHM6Ly93d3cuZ2V0cG9zdG1hbi5jb20iLCJodHRwczovLzEwLjI3LjI2Ljk4OjkyMTAiLCJodHRwczovLzEwLjIwMC4yNS4xNDg6OTIxMCIsImh0dHA6Ly90cy1jaS1rOHMuYmV0cmFkYXIuY29tIiwiaHR0cHM6Ly90cy1jaS1rOHMuc3BvcnRyYWRhci5hZyIsImh0dHA6Ly90cy1jaS1rOHMuc3BvcnRyYWRhci5hZyIsImh0dHA6Ly8xMC4yMDAuMjUuMTQ4OjkyMTAiLCJodHRwczovLzEwLjIwMC4yNS4yNTQ6OTIxMCIsImh0dHA6Ly9sb2NhbGhvc3Q6ODA4OSJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsibXRzX3N1cHBvcnRfdG9vbCIsIlJEUysgUm9sZSIsIm10c19yaXNrX21vbml0b3JpbmciLCJGRFMgUm9sZSIsIlJHUysgUm9sZSIsIm10c19ib2FyZCIsIm10c19jb25zb2xlIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsibXRzLWVkZ2UtaW50Ijp7InJvbGVzIjpbInVzZXIiXX0sIm10cy1lZGdlLWV4dCI6eyJyb2xlcyI6WyJ1c2VyIl19LCJtdHMtYXBpLWdhdGV3YXkiOnsicm9sZXMiOlsibXRzLWFwaS5jbGllbnQtYXBpLm1heC1zdGFrZSIsIm10cy1hcGkuY2xpZW50LWFwaS5jY2YiLCJtdHMtYXBpLnJlcG9ydGluZy5jY2YuZXhwLmhpc3QtY2hnLmNsaWVudGFwaSJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJtdHMtYXBpLmNsaWVudC1hcGkubWF4LXN0YWtlIG10cy1hcGkuY2xpZW50LWFwaS5jY2YgbXRzLWFwaS5yZXBvcnRpbmcuY2NmLmV4cC5oaXN0LWNoZy5jbGllbnRhcGkiLCJuYW1lIjoiRGF2aWQgSHJvdmF0IiwibXRzUHJvZmlsZSI6eyJtYXN0ZXJQcm9maWxlIjp0cnVlLCJwcm9maWxlSWQiOjAsInByb2ZpbGVOYW1lIjoiU3BvcnRyYWRhciIsImJvb2ttYWtlcnMiOltdLCJzdWJCb29rbWFrZXJzIjpbXSwidENoYW5uZWxzIjpbXX0sImdpdmVuX25hbWUiOiJEYXZpZCIsImZhbWlseV9uYW1lIjoiSHJvdmF0IiwiZW1haWwiOiJkLmhyb3ZhdEBzcG9ydHJhZGFyLmNvbSIsInVzZXJuYW1lIjoiZC5ocm92YXQifQ.YyIABHI3XRP3NNsFxiUS6ebYPMYWQvQ6-uBSrAAFL-hwfh6rEq7jQeIVWVBO1o0GRPa2B0iBLsu7UQnYIn3AlYYHozfUEXUUDHtvzzxWlVBA_MxZrW-2Q3eSJi5_gnyCfF46n-z_wZH2rO5h-WQVxRl65QtA7jngdUsl2cDJRjklhpa0hoqIKVl5FJnsWlh65BS2qGoxvAG87QJhcjKGpDoctkyrxE0IYBAFgjA2kTWTcItLHikrTFuTSlRwQ3x0ryqVF-sU3ykBX0BFjJNXwdzmE38qRgEGbklbRUkNrI8tooP4UHKq6f_LWtZdFyvz_TdWYTNg2WCd_ZK0JUP12rH3DYJ3co6hdA-i7_CfD4inexLfuTkXPD8cTDN66bx1jSK8wqZE1Xn2OWidSCrfC63LzJ8r4UHpiMh1bkEN0ARKJ3IOu6QHXfK2eFIg-MPHHlSNlWuf6cgSCbCOOCac8OnDF008qbx7eFqtdd521BKLzmLyBgTUlGR1jdKn4Bx6pWyfZbWiTd0gRn3BG3uUfIVrDKlnqju1DnEYIWoIDVwTqTBK2cYZNqm251UClhP6-0qhd9LqDv7A8VjtotlV-TIPohMz4PUJ8ICwtjAMdv7-6MbCmQVkVXrkv3aAid875yTx87Qj-ULD8IHCoosH_kVl9GUmYGQrqP-aNbYRvwM",
  "expires_in": 3600,
  "refresh_expires_in": 3600,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmNThlNzJmZi03MzhkLTQwYzQtOWFiYy01OTZiOTRlYjlhM2IifQ.eyJleHAiOjE2MTYxNTI3ODcsImlhdCI6MTYxNjE0OTE4NywianRpIjoiMDA2NDkyNzMtN2FlMi00NWM5LWEyMDctMzI2NDA5MDk1ZjJhIiwiaXNzIjoiaHR0cHM6Ly9tdHMtYXV0aC1jaS5iZXRyYWRhci5jb20vYXV0aC9yZWFsbXMvbXRzIiwiYXVkIjoiaHR0cHM6Ly9tdHMtYXV0aC1jaS5iZXRyYWRhci5jb20vYXV0aC9yZWFsbXMvbXRzIiwic3ViIjoiOTA4MTE5NDQtNGY4MS00NDZkLThiZjQtZmU4NmI1ZjYwZWZhIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6Im10cy1lZGdlLWludCIsInNlc3Npb25fc3RhdGUiOiI1ZjYxZmE5Mi00YzFhLTRhZWQtYmVjMC0wZTdjMmQ3ZmRjOWYiLCJzY29wZSI6Im10cy1hcGkuY2xpZW50LWFwaS5tYXgtc3Rha2UgbXRzLWFwaS5jbGllbnQtYXBpLmNjZiBtdHMtYXBpLnJlcG9ydGluZy5jY2YuZXhwLmhpc3QtY2hnLmNsaWVudGFwaSJ9.LIXobqtANMWZPv1M58jBhzJ3R_BS0DDzBB8ojUkXFl4",
  "token_type": "bearer",
  "not-before-policy": 1509654421,
  "session_state": "5f61fa92-4c1a-4aed-bec0-0e7c2d7fdc9f",
  "scope": ""
}
